[2024-07-12T11:34:28.690+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_data_processing_pipeline.process_data manual__2024-07-12T11:28:15.532956+00:00 [queued]>
[2024-07-12T11:34:28.693+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_data_processing_pipeline.process_data manual__2024-07-12T11:28:15.532956+00:00 [queued]>
[2024-07-12T11:34:28.693+0000] {taskinstance.py:1359} INFO - Starting attempt 5 of 6
[2024-07-12T11:34:28.698+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_data> on 2024-07-12 11:28:15.532956+00:00
[2024-07-12T11:34:28.700+0000] {standard_task_runner.py:57} INFO - Started process 1684 to run task
[2024-07-12T11:34:28.702+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_data_processing_pipeline', 'process_data', 'manual__2024-07-12T11:28:15.532956+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/spark-jobs_.py', '--cfg-path', '/tmp/tmpen03x0xu']
[2024-07-12T11:34:28.703+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask process_data
[2024-07-12T11:34:28.728+0000] {task_command.py:415} INFO - Running <TaskInstance: spark_data_processing_pipeline.process_data manual__2024-07-12T11:28:15.532956+00:00 [running]> on host c553c98b8e80
[2024-07-12T11:34:28.769+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_data_processing_pipeline' AIRFLOW_CTX_TASK_ID='process_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-12T11:28:15.532956+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-12T11:28:15.532956+00:00'
[2024-07-12T11:34:28.770+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-12T11:34:28.771+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'bash /opt/***/jobs/spark-submit.sh /opt/***/jobs/main.py']
[2024-07-12T11:34:28.777+0000] {subprocess.py:86} INFO - Output:
[2024-07-12T11:34:28.785+0000] {subprocess.py:93} INFO - /opt/***/jobs/main.py
[2024-07-12T11:34:28.848+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-07-12T11:34:29.858+0000] {subprocess.py:93} INFO - 24/07/12 11:34:29 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-07-12T11:34:30.488+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-07-12T11:34:30.488+0000] {subprocess.py:93} INFO -   File "/opt/***/jobs/main.py", line 5, in <module>
[2024-07-12T11:34:30.488+0000] {subprocess.py:93} INFO -     from base import load_data, init_df, df_with_meta  # Ensure these functions are defined as needed
[2024-07-12T11:34:30.488+0000] {subprocess.py:93} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-07-12T11:34:30.488+0000] {subprocess.py:93} INFO -   File "/opt/***/jobs/base.py", line 6, in <module>
[2024-07-12T11:34:30.488+0000] {subprocess.py:93} INFO -     가
[2024-07-12T11:34:30.489+0000] {subprocess.py:93} INFO - NameError: name '가' is not defined
[2024-07-12T11:34:30.518+0000] {subprocess.py:93} INFO - 24/07/12 11:34:30 INFO ShutdownHookManager: Shutdown hook called
[2024-07-12T11:34:30.518+0000] {subprocess.py:93} INFO - 24/07/12 11:34:30 INFO ShutdownHookManager: Deleting directory /tmp/spark-ef849e1f-fbc4-4a68-91ff-95feb0e91ef2
[2024-07-12T11:34:30.543+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-12T11:34:30.551+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-12T11:34:30.552+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_data_processing_pipeline, task_id=process_data, execution_date=20240712T112815, start_date=20240712T113428, end_date=20240712T113430
[2024-07-12T11:34:30.559+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task process_data (Bash command failed. The command returned a non-zero exit code 1.; 1684)
[2024-07-12T11:34:30.566+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-12T11:34:30.579+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
